name: client
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

# Add regular dependencies here.
dependencies:
  common: ^1.0.0


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
