name: televerse_example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.9.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  televerse: ^3.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
