name: student_missed
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  path: ^1.9.0
  excel: ^4.0.6
  drift: ^2.20.0
  sqlite3: ^2.4.0 

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  drift_dev: ^2.20.0
  build_runner: ^2.4.0
  
