name: tic_tac_toe_net
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

workspace:
  - packages/common
  - packages/server
  - packages/client

# Add regular dependencies here.
dependencies:
  path: ^1.9.0


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0







  
