name: tic_tac_toe
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.9.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.6  
  # sqlite3: '>=2.9.3 <3.0.0'  

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
