name: dart_drift_ex
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  path: ^1.9.0
  drift: ^2.29.0
  sqlite3: ^2.9.4

dev_dependencies:
  lints: ^6.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.10.2
