name: server
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'
resolution: workspace

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.6  
  sqlite3: '>=2.9.3 <3.0.0'  
  #На этом уровне имена подключаемых пакетов
  common: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
