name: student_missed_bot
description: A Telegram bot for student attendance management with SQLite database.
version: 1.0.0

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  televerse: ^3.0.1
  sqflite_common_ffi: ^2.3.6  
  sqlite3: ^2.4.0
  path: ^1.9.0
  excel: ^4.0.6


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6